ALTER TABLE VENDA ADD COLUMN STATUS VARCHAR(20);
ALTER TABLE VENDA MODIFY COLUMN VALOR DECIMAL(10,2);

ALTER TABLE VENDA DROP COLUMN USUARIO;
ALTER TABLE VENDA ADD COLUMN CLIENTE INT(11);


SELECT CONSTRAINT_NAME 
FROM information_schema.KEY_COLUMN_USAGE 
WHERE TABLE_NAME = 'VENDA' 
AND COLUMN_NAME = 'USUARIO';


#ALTER TABLE VENDA DROP FOREIGN KEY venda_ibfk_3;


ALTER TABLE VENDA 
ADD CONSTRAINT fk_vendas_clientes  FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(ID) 
ON DELETE CASCADE;

ALTER TABLE VENDA MODIFY COLUMN STATUS VARCHAR(20) AFTER CLIENTE