-- CRIANDO TABELA CATEGORIA
CREATE TABLE categoria (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  descricao VARCHAR(40) DEFAULT NULL,
  status_categoria CHAR(1) DEFAULT 'A'
) ;

-- CRIANDO TABELA PERFIL
CREATE TABLE perfil (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  descricao VARCHAR(40) DEFAULT NULL
) ;

-- INSERINDO DADOS INICIAIS NA TABELA PERFIL
INSERT INTO perfil (id, descricao) VALUES
(1, 'Administrador'),
(2, 'Usuario');

-- CRIANDO TABELA USUARIO
CREATE TABLE usuario (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) DEFAULT NULL,
  usuario VARCHAR(60) DEFAULT NULL,
  senha VARCHAR(100) DEFAULT NULL,
  perfil INT(11) DEFAULT NULL,
  email VARCHAR(80) DEFAULT NULL,
  cep VARCHAR(20) NOT NULL,
  logradouro VARCHAR(250) NOT NULL,
  numero VARCHAR(10),
  bairro VARCHAR(250) NOT NULL,
  cidade VARCHAR(250) NOT NULL,
  uf VARCHAR(2),
  imagem VARCHAR(100) DEFAULT NULL,
  ativo TINYINT(1) DEFAULT 1
) ;

-- CRIANDO TABELA PRODUTOS
CREATE TABLE produto (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  codigo VARCHAR(6) DEFAULT NULL,
  data_cadastro DATETIME DEFAULT NULL,
  nome VARCHAR(40) DEFAULT NULL,
  descricao VARCHAR(255) DEFAULT NULL,
  quantidade INT(11) DEFAULT NULL,
  cor VARCHAR(40) DEFAULT NULL,
  preco DECIMAL(10,2) DEFAULT NULL,
  desconto DECIMAL(10,2) DEFAULT NULL,
  imagem VARCHAR(100) DEFAULT NULL,
  categoria INT(11) DEFAULT NULL,
  status_produto CHAR(1) DEFAULT 'A',
  preco_custo DECIMAL(10,2) DEFAULT NULL
) ;
-- ATERANDO A COLUNA CODIGO DA  TABELA PRODUTO
ALTER TABLE produto ADD UNIQUE KEY codigo (codigo);

-- CRIANDO TABELA VENDA
CREATE TABLE venda (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  data_venda DATETIME DEFAULT NULL,
  valor DECIMAL(10,2) DEFAULT NULL,
  usuario INT(11) DEFAULT NULL
) ;

-- CRIANDO TABELA ITENS VENDA
CREATE TABLE itens_venda (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  venda INT(11) DEFAULT NULL,
  produto INT(11) DEFAULT NULL,
  quantidade INT(11) DEFAULT NULL,
  preco_unitario DECIMAL(10,2) DEFAULT NULL,
  FOREIGN KEY (venda) REFERENCES venda(id),
  FOREIGN KEY (produto) REFERENCES produto(id)
) ;
CREATE TABLE clientes(
   id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
   nome VARCHAR(250) NOT NULL,
   cpf  VARCHAR(20) NOT NULL,
   data_nascimento DATE,
   email VARCHAR(250)  NOT NULL,
   senha  VARCHAR(120)  NOT NULL,
   cep VARCHAR(20) NOT NULL,
   logradouro VARCHAR(250) NOT NULL,
   numero VARCHAR(10),
   bairro VARCHAR(250) NOT NULL,
   cidade VARCHAR(250) NOT NULL,
   uf VARCHAR(2),
   imagem VARCHAR(120),
   data_cadastro TIMESTAMP,
  ativo TINYINT(1) DEFAULT 1
);